---
plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
    - gemfiles/*
    - pkg/**/*
    - spec/**/*
    - vendor/**/*
    - integration/bin/*
    - integration/spec/**/*

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
