---
name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 4 1 * *'

jobs:
  rspec:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.3'
          - '3.2'
          - '3.1'
          - '3.0'
          - '2.7'
          - '2.6'
        rails:
          - rails_8.0
          - rails_7.2
          - rails_7.1
          - rails_7.0
          - rails_6.1
          - rails_6.0

        exclude:
          - ruby: '2.6'
            rails: 'rails_7.0'
          - ruby: '2.6'
            rails: 'rails_7.1'
          - ruby: '2.6'
            rails: 'rails_7.2'

          - ruby: '2.7'
            rails: 'rails_7.2'

          - ruby: '3.0'
            rails: 'rails_6.0'
          - ruby: '3.0'
            rails: 'rails_7.2'

          - ruby: '2.6'
            rails: 'rails_8.0'
          - ruby: '2.7'
            rails: 'rails_8.0'
          - ruby: '3.0'
            rails: 'rails_8.0'
          - ruby: '3.1'
            rails: 'rails_8.0'

    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.rails }}.gemfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: RSpec
        run: 'echo "current_directory: ${PWD}" && bin/rspec --profile 10 --format RspecJunitFormatter --out ./test-results/rspec/results.xml --format progress'

  rspec-integration:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}/integration

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.3'
          - '3.2'
          - '3.1'
          - '3.0'
          - '2.7'
          - '2.6'
        rails:
          - rails_8.0
          - rails_7.2
          - rails_7.1
          - rails_7.0
          - rails_6.1
          - rails_6.0

        exclude:
          - ruby: '2.6'
            rails: 'rails_7.0'
          - ruby: '2.6'
            rails: 'rails_7.1'
          - ruby: '2.6'
            rails: 'rails_7.2'

          - ruby: '2.7'
            rails: 'rails_7.2'

          - ruby: '3.0'
            rails: 'rails_6.0'
          - ruby: '3.0'
            rails: 'rails_7.2'

          - ruby: '2.6'
            rails: 'rails_8.0'
          - ruby: '2.7'
            rails: 'rails_8.0'
          - ruby: '3.0'
            rails: 'rails_8.0'
          - ruby: '3.1'
            rails: 'rails_8.0'

    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.rails }}.gemfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: RSpec
        run: 'echo "current_directory: ${PWD}" && bin/rspec --profile 10 --format RspecJunitFormatter --out ./test-results/rspec/results.xml --format progress'
